# Generated by Django 5.1 on 2024-08-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('Canada', 'Canada'), ('United Kingdom', 'United Kingdom'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('Australia', 'Australia'), ('Japan', 'Japan'), ('China', 'China'), ('India', 'India'), ('Brazil', 'Brazil'), ('South Africa', 'South Africa'), ('Mexico', 'Mexico'), ('Russia', 'Russia'), ('Argentina', 'Argentina'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Greece', 'Greece'), ('Turkey', 'Turkey'), ('Saudi Arabia', 'Saudi Arabia'), ('United Arab Emirates', 'United Arab Emirates'), ('Singapore', 'Singapore'), ('Malaysia', 'Malaysia'), ('Philippines', 'Philippines'), ('South Korea', 'South Korea'), ('New Zealand', 'New Zealand'), ('Chile', 'Chile'), ('Peru', 'Peru'), ('Colombia', 'Colombia'), ('Ukraine', 'Ukraine'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('Hungary', 'Hungary'), ('Portugal', 'Portugal'), ('Israel', 'Israel'), ('Egypt', 'Egypt'), ('Nigeria', 'Nigeria'), ('Kenya', 'Kenya')], max_length=255),
        ),
    ]
