# Generated by Django 5.1 on 2024-08-08 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_product_seller'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='seller.sellerprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='seller.sellerprofile'),
            preserve_default=False,
        ),
    ]
